version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=freelance
      - POSTGRES_USER=o_p
      - POSTGRES_PASSWORD=#pragma_once
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --ini uwsgi.ini
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
