# Generated by Django 3.1.3 on 2021-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210116_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_mailing',
            field=models.BooleanField(default=False),
        ),
    ]
