# Generated by Django 3.1.3 on 2021-01-31 16:27

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_code',
            field=creditcards.models.SecurityCodeField(blank=True, max_length=4, null=True, verbose_name='CVV/CVC'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry',
            field=creditcards.models.CardExpiryField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=creditcards.models.CardNumberField(blank=True, max_length=25, null=True, verbose_name='Card Number'),
        ),
    ]
