# Generated by Django 3.1.6 on 2021-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210131_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Field updates when user login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Field updates when user login'),
        ),
    ]
