name: freelance-backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Setup Redis
      uses: supercharge/redis-github-action@8dd3c86cd02fabe1bc459d55ba892a9ce91e23c6
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with: 
        postgresql version: 12.2
        postgresql db: 'test'
        postgresql user: 'test_user'
        postgresql password: '1234'
    
#     - name: Cache dependencies
#       uses: actions/cache@master
#       id: cache
#       with:
#         path: /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages
#         key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#         restore-keys: |
#           ${{ runner.os }}-pip-
#           ${{ runner.os }}-


    - name: Install dependencies
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd app
        pytest --ignore=sendgrid
