# Generated by Django 3.1.3 on 2021-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210128_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
