# Generated by Django 3.1.6 on 2021-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_performer',
            field=models.BooleanField(default=False),
        ),
    ]
