# Generated by Django 3.1.6 on 2021-03-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_is_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
