# Generated by Django 3.1.6 on 2021-03-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='is_performer',
            new_name='has_performer',
        ),
    ]
